"""Compatibility shim for the genres domain."""

from crate.db.queries.genres import (
    get_all_genres,
    get_albums_with_genres,
    get_artist_album_genres,
    get_artists_missing_genre_mapping,
    get_artists_with_tags,
    get_genre_cooccurring_album_slugs,
    get_genre_cooccurring_artist_slugs,
    get_genre_detail,
    get_genre_graph,
    get_genre_seed_artists,
    get_genre_taxonomy_cover_path,
    get_genre_taxonomy_node_id,
    get_remaining_without_external_description,
    get_total_genre_count,
    get_unmapped_genre_count,
    get_unmapped_genres,
    list_genre_taxonomy_nodes_for_external_enrichment,
    list_genre_taxonomy_nodes_for_musicbrainz_sync,
    list_invalid_genre_taxonomy_nodes,
    list_unmapped_genres_for_inference,
)
from crate.db.repositories.genres import (
    cleanup_invalid_genre_taxonomy_nodes,
    get_or_create_genre,
    set_album_genres,
    set_artist_genres,
    set_artist_taxonomy_genres,
    set_genre_eq_gains,
    update_genre_external_metadata,
    upsert_genre_taxonomy_edge,
    upsert_genre_taxonomy_node,
)

__all__ = [
    "cleanup_invalid_genre_taxonomy_nodes",
    "get_all_genres",
    "get_albums_with_genres",
    "get_artist_album_genres",
    "get_artists_missing_genre_mapping",
    "get_artists_with_tags",
    "get_genre_cooccurring_album_slugs",
    "get_genre_cooccurring_artist_slugs",
    "get_genre_detail",
    "get_genre_graph",
    "get_genre_seed_artists",
    "get_genre_taxonomy_cover_path",
    "get_genre_taxonomy_node_id",
    "get_or_create_genre",
    "get_remaining_without_external_description",
    "get_total_genre_count",
    "get_unmapped_genre_count",
    "get_unmapped_genres",
    "list_genre_taxonomy_nodes_for_external_enrichment",
    "list_genre_taxonomy_nodes_for_musicbrainz_sync",
    "list_invalid_genre_taxonomy_nodes",
    "list_unmapped_genres_for_inference",
    "set_album_genres",
    "set_artist_genres",
    "set_artist_taxonomy_genres",
    "set_genre_eq_gains",
    "update_genre_external_metadata",
    "upsert_genre_taxonomy_edge",
    "upsert_genre_taxonomy_node",
]
