"""Legacy compatibility shim for playlist access.

New runtime code should import from ``crate.db.repositories.playlists``.
This module remains only to keep the deprecated compat surface and older
tests/scripts working while the backend migration finishes.
"""

from crate.db.repositories.playlists import (
    add_playlist_member,
    add_playlist_tracks,
    can_edit_playlist,
    can_view_playlist,
    consume_playlist_invite,
    create_playlist,
    create_playlist_invite,
    delete_playlist,
    duplicate_playlist,
    execute_smart_rules,
    follow_playlist,
    get_followed_system_playlists,
    get_generation_history,
    get_playlist,
    get_playlist_filter_options,
    get_playlist_followers_count,
    get_playlist_member,
    get_playlist_members,
    get_playlist_tracks,
    get_playlists,
    get_smart_playlists_for_refresh,
    generate_by_artist,
    generate_by_decade,
    generate_by_genre,
    generate_random,
    generate_similar_artists,
    is_playlist_followed,
    is_playlist_owner,
    list_system_playlists,
    log_generation_complete,
    log_generation_failed,
    log_generation_start,
    regenerate_playlist_tracks,
    remove_playlist_member,
    remove_playlist_track,
    reorder_playlist,
    replace_playlist_tracks,
    set_playlist_track_lock,
    set_generation_status,
    unfollow_playlist,
    update_playlist,
)

__all__ = [
    "add_playlist_member",
    "add_playlist_tracks",
    "can_edit_playlist",
    "can_view_playlist",
    "consume_playlist_invite",
    "create_playlist",
    "create_playlist_invite",
    "delete_playlist",
    "duplicate_playlist",
    "execute_smart_rules",
    "follow_playlist",
    "get_followed_system_playlists",
    "get_generation_history",
    "get_playlist",
    "get_playlist_filter_options",
    "get_playlist_followers_count",
    "get_playlist_member",
    "get_playlist_members",
    "get_playlist_tracks",
    "get_playlists",
    "get_smart_playlists_for_refresh",
    "generate_by_artist",
    "generate_by_decade",
    "generate_by_genre",
    "generate_random",
    "generate_similar_artists",
    "is_playlist_followed",
    "is_playlist_owner",
    "list_system_playlists",
    "log_generation_complete",
    "log_generation_failed",
    "log_generation_start",
    "regenerate_playlist_tracks",
    "remove_playlist_member",
    "remove_playlist_track",
    "reorder_playlist",
    "replace_playlist_tracks",
    "set_playlist_track_lock",
    "set_generation_status",
    "unfollow_playlist",
    "update_playlist",
]
