from __future__ import annotations

from crate.db.repositories.auth_identities import (
    get_user_external_identity,
    list_user_external_identities,
    unlink_user_external_identity,
    upsert_user_external_identity,
)
from crate.db.repositories.auth_invites import (
    consume_auth_invite,
    create_auth_invite,
    get_auth_invite,
    list_auth_invites,
)
from crate.db.repositories.auth_sessions import (
    cleanup_ended_jam_rooms,
    cleanup_expired_sessions,
    create_session,
    delete_session,
    get_session,
    list_sessions,
    revoke_other_sessions,
    revoke_session,
    touch_session,
)
from crate.db.repositories.auth_users import (
    _seed_admin,
    count_users,
    create_user,
    delete_user,
    get_user_by_email,
    get_user_by_external_identity,
    get_user_by_google_id,
    get_user_by_id,
    get_user_presence,
    get_users_presence,
    list_users,
    list_users_map_rows,
    suggest_username,
    update_user,
    update_user_last_login,
    update_user_location,
)

__all__ = [
    "_seed_admin",
    "cleanup_ended_jam_rooms",
    "cleanup_expired_sessions",
    "consume_auth_invite",
    "count_users",
    "create_auth_invite",
    "create_session",
    "create_user",
    "delete_session",
    "delete_user",
    "get_auth_invite",
    "get_session",
    "get_user_by_email",
    "get_user_by_external_identity",
    "get_user_by_google_id",
    "get_user_by_id",
    "get_user_external_identity",
    "get_user_presence",
    "get_users_presence",
    "list_auth_invites",
    "list_sessions",
    "list_user_external_identities",
    "list_users",
    "list_users_map_rows",
    "revoke_other_sessions",
    "revoke_session",
    "suggest_username",
    "touch_session",
    "unlink_user_external_identity",
    "update_user",
    "update_user_last_login",
    "update_user_location",
    "upsert_user_external_identity",
]
