"""Compatibility facade for library repository helpers."""

from __future__ import annotations

from crate.db.repositories.library_reads import (
    enrich_track_refs,
    find_user_playlist_by_name,
    get_album_quality_map,
    get_albums_missing_covers,
    get_artist_analysis_tracks,
    get_artist_refs_by_names,
    get_artist_tracks_for_setlist,
    get_library_album,
    get_library_album_by_entity_uid,
    get_library_album_by_id,
    get_library_albums,
    get_library_artist,
    get_library_artist_by_entity_uid,
    get_library_artist_by_id,
    get_library_artist_by_slug,
    get_library_artists,
    get_library_stats,
    get_library_track_by_entity_uid,
    get_library_track_by_id,
    get_library_track_by_path,
    get_library_track_count,
    get_library_tracks,
    get_library_tracks_by_entity_uids,
    resolve_library_track_reference,
    get_release_by_id,
    get_track_path_by_id,
    get_track_rating,
)
from crate.db.repositories.library_track_reads import (
    get_library_track_by_storage_id,
    get_library_tracks_by_storage_ids,
)
from crate.db.repositories.library_writes import (
    delete_album,
    delete_artist,
    delete_quarantined_album,
    delete_track,
    quarantine_album,
    set_track_rating,
    unquarantine_album,
    update_artist_enrichment,
    update_artist_has_photo,
    update_track_analysis,
    upsert_album,
    upsert_artist,
    upsert_track,
)


__all__ = [
    "delete_album",
    "delete_artist",
    "delete_quarantined_album",
    "delete_track",
    "enrich_track_refs",
    "find_user_playlist_by_name",
    "get_album_quality_map",
    "get_albums_missing_covers",
    "get_artist_analysis_tracks",
    "get_artist_refs_by_names",
    "get_artist_tracks_for_setlist",
    "get_library_album",
    "get_library_album_by_entity_uid",
    "get_library_album_by_id",
    "get_library_albums",
    "get_library_artist",
    "get_library_artist_by_entity_uid",
    "get_library_artist_by_id",
    "get_library_artist_by_slug",
    "get_library_artists",
    "get_library_stats",
    "get_library_track_by_entity_uid",
    "get_library_track_by_id",
    "get_library_track_by_path",
    "get_library_track_by_storage_id",
    "get_library_track_count",
    "get_library_tracks",
    "get_library_tracks_by_entity_uids",
    "get_library_tracks_by_storage_ids",
    "resolve_library_track_reference",
    "get_release_by_id",
    "get_track_path_by_id",
    "get_track_rating",
    "quarantine_album",
    "set_track_rating",
    "unquarantine_album",
    "update_artist_enrichment",
    "update_artist_has_photo",
    "update_track_analysis",
    "upsert_album",
    "upsert_artist",
    "upsert_track",
]
