"""Compatibility facade for playlist repository helpers."""

from __future__ import annotations

from crate.db.repositories.playlists_generation import (
    execute_smart_rules,
    generate_by_artist,
    generate_by_decade,
    generate_by_genre,
    generate_random,
    generate_similar_artists,
    log_generation_complete,
    log_generation_failed,
    log_generation_start,
    set_generation_status,
)
from crate.db.repositories.playlists_reads import (
    can_edit_playlist,
    can_view_playlist,
    get_followed_system_playlists,
    get_generation_history,
    get_playlist,
    get_playlist_filter_options,
    get_playlist_followers_count,
    get_playlist_member,
    get_playlist_members,
    get_playlist_tracks,
    get_playlists,
    get_public_system_playlists_for_artist,
    get_smart_playlists_for_refresh,
    get_system_playlist_by_curation_key,
    is_playlist_followed,
    is_playlist_owner,
    list_system_playlists,
)
from crate.db.repositories.playlists_writes import (
    add_playlist_member,
    add_playlist_tracks,
    consume_playlist_invite,
    create_playlist,
    create_playlist_invite,
    delete_playlist,
    duplicate_playlist,
    follow_playlist,
    remove_playlist_member,
    remove_playlist_track,
    replace_playlist_tracks,
    reorder_playlist,
    unfollow_playlist,
    update_playlist,
)


__all__ = [
    "add_playlist_member",
    "add_playlist_tracks",
    "can_edit_playlist",
    "can_view_playlist",
    "consume_playlist_invite",
    "create_playlist",
    "create_playlist_invite",
    "delete_playlist",
    "duplicate_playlist",
    "execute_smart_rules",
    "follow_playlist",
    "generate_by_artist",
    "generate_by_decade",
    "generate_by_genre",
    "generate_random",
    "generate_similar_artists",
    "get_followed_system_playlists",
    "get_generation_history",
    "get_playlist",
    "get_playlist_filter_options",
    "get_playlist_followers_count",
    "get_playlist_member",
    "get_playlist_members",
    "get_playlist_tracks",
    "get_playlists",
    "get_public_system_playlists_for_artist",
    "get_smart_playlists_for_refresh",
    "get_system_playlist_by_curation_key",
    "is_playlist_followed",
    "is_playlist_owner",
    "list_system_playlists",
    "log_generation_complete",
    "log_generation_failed",
    "log_generation_start",
    "remove_playlist_member",
    "remove_playlist_track",
    "replace_playlist_tracks",
    "reorder_playlist",
    "set_generation_status",
    "unfollow_playlist",
    "update_playlist",
]
